name: vekolo
description: "Workout cycling as it should be"
publish_to: 'none' # never publish!

version: 0.5.1+2

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  flutter_blue_plus: ^1.36.8
  go_router: ^17.0.0
  context_plus: ^6.0.6
  async: ^2.13.0
  permission_handler: ^12.0.1
  dio: ^5.7.0
  flutter_secure_storage: ^9.2.2
  deep_pick: ^1.1.0
  reactive_forms: ^18.1.1
  state_beacon: ^1.0.0
  clock: ^1.0.0
  fresh_dio:
  url_launcher: ^6.3.2
  device_info_plus: ^12.2.0
  visibility_detector: ^0.4.0+2
  shared_preferences: ^2.5.0
  nanoid2: ^2.0.1
  path_provider: ^2.1.5
  google_fonts: ^6.2.1
  wiredash: ^2.4.0
  chirp:
    git:
      url: git@github.com:passsy/chirp.git
      ref: main
  flutter_svg: ^2.2.2
  synchronized: ^3.4.0

dev_dependencies:
  flutter_blue_plus_platform_interface: ^7.0.0
  flutter_test:
    sdk: flutter
  lint: ^2.8.0
  spot: ^0.18.0
  fake_async: ^1.3.1
  path_provider_platform_interface: ^2.1.2
  plugin_platform_interface: ^2.1.8

  meta: any
  test_api: any
  shared_preferences_platform_interface: any
  stack_trace: any
  matcher: any
  leak_tracker: any
  leak_tracker_testing: any
  collection: any
  dartx: any
dependency_overrides:
  fresh_dio:
    git:
      url: https://github.com/passsy/fresh/
      path: packages/fresh_dio
      ref: pull-validate-token-from-StarProxima
  fresh:
    git:
      url: https://github.com/passsy/fresh/
      path: packages/fresh
      ref: pull-validate-token-from-StarProxima
#  chirp:
#    path: /Users/pascalwelsch/Projects/passsy/chirp
flutter:
  uses-material-design: true
  assets:
    - save.json
    - assets/fonts/
    - assets/images/logo-outline.svg
    - assets/images/logo-filled.svg
